/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useState } from "react";
import profile from "../assets/profile.png";

export default function Test() {
  const [dialogFlag, setDialogFlag] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style></style>
      </Head>
      <div className="w-screen h-screen flex flex-col items-center justify-center gap-5 bg-primary">
        {/* <div className="bg-red-500 w-full h-1/2 absolute top-0" ></div>
        <div className="bg-red-500 w-full h-1/2 absolute bottom-0"></div> */}
        {/* <div className="flex flex-col border-y-2 h-96 bg-white border-black w-full items-center z-20 relative">
          {" "}
          <div className="flex gap-5 mt-10 z-10">
            <div className="w-80 h-40 border-black  border-2 rounded-xl mt-2 object-cover relative"></div>
            <div className="w-72 h-80 border-black border-2 rounded-xl grid grid-cols-2 py-2 ">
              <div className="col-span-1 h-40 border-2 rounded-xl border-black items-center mx-2 "></div>
              <div className="col-span-1 h-40 border-2 rounded-xl border-black items-center mx-2 "></div>
            </div>
            <div className="w-80 h-40 border-black border-2 rounded-xl mt-2"></div>
            <div className="w-80 h-40 border-black border-2 rounded-xl mt-2"></div>
          </div>
          <div className="w-full h-0.5 bg-black absolute">s</div>
        </div> */}
        {/* <div className="relative w-full bg-white h-[50vh] z-0">
          <div className="w-full h-full grid grid-cols-4 z-20 gap-10">
            {[...Array(4).keys()].map((i) => (
              <div
                key={i}
                className="w-full h-1/2 my-auto relative overflow-hidden border-2 border-black rounded-xl"
              >
                <div className="w-full h-full overflow-clip">
                  <img
                    src="https://picsum.photos/1900/1000"
                    className="absolute w-full h-96 top-0"
                    alt=""
                  />
                </div>
              </div>
            ))}
          </div>
        </div> */}
        {/* <div className="h-1/3 w-full flex items-center bg-white"> */}
        {/* </div> */}

        {/* <div
          className="relative z-10 w-full h-[50vh]"
          style={{
            background: "url(https://picsum.photos/1900/500)",
            backgroundRepeat: "no-repeat",
            backgroundAttachment: "fixed",
            backgroundSize: "cover",
          }}
        >
          <div
            className="w-full h-full bg-white absolute top-0 left-0 "
            style={{
              clipPath: `polygon(0% 0%, 0% 100%, 10% 100%, 10% 25%, 30% 25%, 30% 75%, 10% 75%, 10% 100%, 0% 0%, 0% 100%, 50% 100%, 50% 25%, 75% 25%, 75% 75%, 50% 75%, 50% 100%, 100% 100%, 100% 0%)`,
            }}
          ></div> */}
        {/* <div
            className="w-full h-full bg-red-300 absolute top-0 left-0"
            style={{
              clipPath:
                "polygon(0% 0%, 0% 100%, 50% 100%, 50% 25%, 75% 25%, 75% 75%, 50% 75%, 50% 100%, 100% 100%, 100% 0%)",
            }}
          ></div>
        </div> */}
        {/* <svg
          id="Layer_1"
          className="z-10 relative"
          data-name="Layer 1"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 1920 1080"
        >
          {" "}
          <defs> </defs>{" "}
          <path
            style={{
              fill: "#b74949",
            }}
            d="M0,0 V1080 H1920 V0 H0 Z M548,496H177V255h371v241Zm412,0h-371V255h371v241Zm403,0h-371V255h371v241Zm406,0h-371V255h371v241Z"
          />
           
        </svg> */}
        <div className="w-5/6 gap-5 flex items-center">
          <div className="border-white border-4 p-4 flex items-center gap-4 w-1/2">
            {" "}
            <img src={profile.src} alt="richardAngkasa" />
            <h1
              className={`${
                dialogFlag ? "hidden" : "block"
              } font-game text-xs test leading-6`}
              onClick={() => {
                setDialogFlag(true);
              }}
            >
              Hi there traveler, please welcome to my humble train
            </h1>{" "}
            <h1
              className={`${
                dialogFlag ? "block" : "hidden"
              } font-game text-xs test`}
            >
              there's not much here, but hey the train is moving!
            </h1>{" "}
          </div>
          <div className="flex flex-col gap-2">
            {" "}
            <div className="font-game text-xs test">Work</div>
            <div className="font-game text-xs test">About Me</div>
          </div>
        </div>
      </div>
    </>
  );
}
